### ISSUE TITLE
При добавлении нового аккаунта пользователя при дублированном логине невозможно добавить аккаунт.

### ISSUE THREAD

**Issue by Nek-12** [Jornwer/Coursework-1-BSUIR#4]
https://youtu.be/SqeIiszlaYM

**Comment by Jornwer** [comment]
Так и задумано.

**Comment by Nek-12** [comment]
Проблема в том, что аккаунт не добавляется, что бы я ни вводил, хотя написано "повторите ввод". Какой ввод?

**Comment by Jornwer** [comment]
Поменял текстовые сообщения

**Comment by Jornwer** [comment]
Исправил
