### ISSUE TITLE
Невозможно переключиться на другой ряд при добавлении автомобиля в каталог

### ISSUE THREAD

**Issue by Nek-12** [Jornwer/Coursework-1-BSUIR#6]
Использование стрелочек вместо переключения вводит буквы P,H и т.д.
https://youtu.be/WJLqv6pGbhA

**Comment by Jornwer** [comment]
Исправил

**Comment by Nek-12** [comment]
Не исправил
![image](https://user-images.githubusercontent.com/46318640/79604227-613e3b80-80f6-11ea-83c5-635be2c2c013.png)
