### ISSUE TITLE
Критические ошибки каталога (3)

### ISSUE THREAD

**Issue by Nek-12** [Jornwer/Coursework-1-BSUIR#7]
1. Вместо фразы "страницы 1 из x" отображаются иероглифы.
2. При удалении записей из каталога их страницы не удаляются, даже если они пустые
3. Если удалить все записи из каталога и попытаться удалить ещё одну (нажать enter), будет уничтожена память (удалён несуществующий элемент)
![image](https://user-images.githubusercontent.com/46318640/79600935-ad867d00-80f0-11ea-8542-f628dc1d0cdf.png)
![image](https://user-images.githubusercontent.com/46318640/79600963-b8d9a880-80f0-11ea-8ae8-e47f600f7b66.png)

**Comment by Nek-12** [comment]
Если удалить не все элементы, а только элементы с одной страницы, потом перейти на эту страницу и удалить пустой элемент, произойдёт то же самое, что и при удалении элемента из пустого каталога.

**Comment by Jornwer** [comment]
1 исправил

**Comment by Jornwer** [comment]
Все исправил
