### ISSUE TITLE
Отсутствуют проверки на валидность данных в файлах

### ISSUE THREAD

**Issue by Nek-12** [Jornwer/Coursework-1-BSUIR#9]
При порче файла программа продолжает работать как ни в чём не бывало, игнорируя уничтоженный файл
![image](https://user-images.githubusercontent.com/46318640/79602906-060b4980-80f4-11ea-8888-43f9d4ec5bd3.png)
[catalog.txt](https://github.com/Jornwer/Coursework-1-BSUIR/files/4494670/catalog.txt)

**Comment by Jornwer** [comment]
Исправил
